<?php


/**
 *  Numeric entity resolver
 *  @name    ScaffoldTemplateEntityNumeric
 *  @package Scaffold
 *  @author  Rogier Spieker <rogier@konfirm.net>
 */
class ScaffoldTemplateEntityNumeric extends Konsolidate
{
	static public $resolve = Array(
		'excl' => 33, //  exclamation mark
		'quot' => 34, //  quotation mark
		'QUOT' => 34,
		'num' => 35, //  number sign
		'dollar' => 36, //  dollar sign
		'percnt' => 37, //  percent sign
		'amp' => 38, //  ampersand
		'AMP' => 38,
		'apos' => 39, //  apostrophe
		'lpar' => 40, //  left parenthesis
		'rpar' => 41, //  right parenthesis
		'ast' => 42, //  asterisk
		'midast' => 42,
		'plus' => 43, //  plus sign
		'comma' => 44, //  comma
		'period' => 46, //  full stop
		'sol' => 47, //  solidus
		'colon' => 58, //  colon
		'semi' => 59, //  semicolon
		'lt' => 60, //  less-than sign
		'LT' => 60,
		'equals' => 61, //  equals sign
		'gt' => 62, //  greater-than sign
		'GT' => 62,
		'quest' => 63, //  question mark
		'commat' => 64, //  commercial at
		'lsqb' => 91, //  left square bracket
		'lbrack' => 91,
		'bsol' => 92, //  reverse solidus
		'rsqb' => 93, //  right square bracket
		'rbrack' => 93,
		'Hat' => 94, //  circumflex accent
		'lowbar' => 95, //  low line
		'grave' => 96, //  grave accent
		'DiacriticalGrave' => 96,
		'lcub' => 123, //  left curly bracket
		'lbrace' => 123,
		'verbar' => 124, //  vertical line
		'vert' => 124,
		'VerticalLine' => 124,
		'rcub' => 125, //  right curly bracket
		'rbrace' => 125,
		'nbsp' => 160, //  no-break space
		'NonBreakingSpace' => 160,
		'iexcl' => 161, //  inverted exclamation mark
		'cent' => 162, //  cent sign
		'pound' => 163, //  pound sign
		'curren' => 164, //  currency sign
		'yen' => 165, //  yen sign
		'brvbar' => 166, //  broken bar
		'sect' => 167, //  section sign
		'Dot' => 168, //  diaeresis
		'die' => 168,
		'DoubleDot' => 168,
		'uml' => 168,
		'copy' => 169, //  copyright sign
		'COPY' => 169,
		'ordf' => 170, //  feminine ordinal indicator
		'laquo' => 171, //  left-pointing double angle quotation mark
		'not' => 172, //  not sign
		'shy' => 173, //  soft hyphen
		'reg' => 174, //  registered sign
		'circledR' => 174,
		'REG' => 174,
		'macr' => 175, //  macron
		'OverBar' => 175,
		'strns' => 175,
		'deg' => 176, //  degree sign
		'plusmn' => 177, //  plus-minus sign
		'pm' => 177,
		'PlusMinus' => 177,
		'sup2' => 178, //  superscript two
		'sup3' => 179, //  superscript three
		'acute' => 180, //  acute accent
		'DiacriticalAcute' => 180,
		'micro' => 181, //  micro sign
		'para' => 182, //  pilcrow sign
		'middot' => 183, //  middle dot
		'centerdot' => 183,
		'CenterDot' => 183,
		'cedil' => 184, //  cedilla
		'Cedilla' => 184,
		'sup1' => 185, //  superscript one
		'ordm' => 186, //  masculine ordinal indicator
		'raquo' => 187, //  right-pointing double angle quotation mark
		'frac14' => 188, //  vulgar fraction one quarter
		'frac12' => 189, //  vulgar fraction one half
		'half' => 189,
		'frac34' => 190, //  vulgar fraction three quarters
		'iquest' => 191, //  inverted question mark
		'Agrave' => 192, //  latin capital letter a with grave
		'Aacute' => 193, //  latin capital letter a with acute
		'Acirc' => 194, //  latin capital letter a with circumflex
		'Atilde' => 195, //  latin capital letter a with tilde
		'Auml' => 196, //  latin capital letter a with diaeresis
		'Aring' => 197, //  latin capital letter a with ring above
		'AElig' => 198, //  latin capital letter ae
		'Ccedil' => 199, //  latin capital letter c with cedilla
		'Egrave' => 200, //  latin capital letter e with grave
		'Eacute' => 201, //  latin capital letter e with acute
		'Ecirc' => 202, //  latin capital letter e with circumflex
		'Euml' => 203, //  latin capital letter e with diaeresis
		'Igrave' => 204, //  latin capital letter i with grave
		'Iacute' => 205, //  latin capital letter i with acute
		'Icirc' => 206, //  latin capital letter i with circumflex
		'Iuml' => 207, //  latin capital letter i with diaeresis
		'ETH' => 208, //  latin capital letter eth
		'Ntilde' => 209, //  latin capital letter n with tilde
		'Ograve' => 210, //  latin capital letter o with grave
		'Oacute' => 211, //  latin capital letter o with acute
		'Ocirc' => 212, //  latin capital letter o with circumflex
		'Otilde' => 213, //  latin capital letter o with tilde
		'Ouml' => 214, //  latin capital letter o with diaeresis
		'times' => 215, //  multiplication sign
		'Oslash' => 216, //  latin capital letter o with stroke
		'Ugrave' => 217, //  latin capital letter u with grave
		'Uacute' => 218, //  latin capital letter u with acute
		'Ucirc' => 219, //  latin capital letter u with circumflex
		'Uuml' => 220, //  latin capital letter u with diaeresis
		'Yacute' => 221, //  latin capital letter y with acute
		'THORN' => 222, //  latin capital letter thorn
		'szlig' => 223, //  latin small letter sharp s
		'agrave' => 224, //  latin small letter a with grave
		'aacute' => 225, //  latin small letter a with acute
		'acirc' => 226, //  latin small letter a with circumflex
		'atilde' => 227, //  latin small letter a with tilde
		'auml' => 228, //  latin small letter a with diaeresis
		'aring' => 229, //  latin small letter a with ring above
		'aelig' => 230, //  latin small letter ae
		'ccedil' => 231, //  latin small letter c with cedilla
		'egrave' => 232, //  latin small letter e with grave
		'eacute' => 233, //  latin small letter e with acute
		'ecirc' => 234, //  latin small letter e with circumflex
		'euml' => 235, //  latin small letter e with diaeresis
		'igrave' => 236, //  latin small letter i with grave
		'iacute' => 237, //  latin small letter i with acute
		'icirc' => 238, //  latin small letter i with circumflex
		'iuml' => 239, //  latin small letter i with diaeresis
		'eth' => 240, //  latin small letter eth
		'ntilde' => 241, //  latin small letter n with tilde
		'ograve' => 242, //  latin small letter o with grave
		'oacute' => 243, //  latin small letter o with acute
		'ocirc' => 244, //  latin small letter o with circumflex
		'otilde' => 245, //  latin small letter o with tilde
		'ouml' => 246, //  latin small letter o with diaeresis
		'divide' => 247, //  division sign
		'div' => 247,
		'oslash' => 248, //  latin small letter o with stroke
		'ugrave' => 249, //  latin small letter u with grave
		'uacute' => 250, //  latin small letter u with acute
		'ucirc' => 251, //  latin small letter u with circumflex
		'uuml' => 252, //  latin small letter u with diaeresis
		'yacute' => 253, //  latin small letter y with acute
		'thorn' => 254, //  latin small letter thorn
		'yuml' => 255, //  latin small letter y with diaeresis
		'Amacr' => 256, //  latin capital letter a with macron
		'amacr' => 257, //  latin small letter a with macron
		'Abreve' => 258, //  latin capital letter a with breve
		'abreve' => 259, //  latin small letter a with breve
		'Aogon' => 260, //  latin capital letter a with ogonek
		'aogon' => 261, //  latin small letter a with ogonek
		'Cacute' => 262, //  latin capital letter c with acute
		'cacute' => 263, //  latin small letter c with acute
		'Ccirc' => 264, //  latin capital letter c with circumflex
		'ccirc' => 265, //  latin small letter c with circumflex
		'Cdot' => 266, //  latin capital letter c with dot above
		'cdot' => 267, //  latin small letter c with dot above
		'Ccaron' => 268, //  latin capital letter c with caron
		'ccaron' => 269, //  latin small letter c with caron
		'Dcaron' => 270, //  latin capital letter d with caron
		'dcaron' => 271, //  latin small letter d with caron
		'Dstrok' => 272, //  latin capital letter d with stroke
		'dstrok' => 273, //  latin small letter d with stroke
		'Emacr' => 274, //  latin capital letter e with macron
		'emacr' => 275, //  latin small letter e with macron
		'Edot' => 278, //  latin capital letter e with dot above
		'edot' => 279, //  latin small letter e with dot above
		'Eogon' => 280, //  latin capital letter e with ogonek
		'eogon' => 281, //  latin small letter e with ogonek
		'Ecaron' => 282, //  latin capital letter e with caron
		'ecaron' => 283, //  latin small letter e with caron
		'Gcirc' => 284, //  latin capital letter g with circumflex
		'gcirc' => 285, //  latin small letter g with circumflex
		'Gbreve' => 286, //  latin capital letter g with breve
		'gbreve' => 287, //  latin small letter g with breve
		'Gdot' => 288, //  latin capital letter g with dot above
		'gdot' => 289, //  latin small letter g with dot above
		'Gcedil' => 290, //  latin capital letter g with cedilla
		'Hcirc' => 292, //  latin capital letter h with circumflex
		'hcirc' => 293, //  latin small letter h with circumflex
		'Hstrok' => 294, //  latin capital letter h with stroke
		'hstrok' => 295, //  latin small letter h with stroke
		'Itilde' => 296, //  latin capital letter i with tilde
		'itilde' => 297, //  latin small letter i with tilde
		'Imacr' => 298, //  latin capital letter i with macron
		'imacr' => 299, //  latin small letter i with macron
		'Iogon' => 302, //  latin capital letter i with ogonek
		'iogon' => 303, //  latin small letter i with ogonek
		'Idot' => 304, //  latin capital letter i with dot above
		'imath' => 305, //  latin small letter dotless i
		'inodot' => 305,
		'IJlig' => 306, //  latin capital ligature ij
		'ijlig' => 307, //  latin small ligature ij
		'Jcirc' => 308, //  latin capital letter j with circumflex
		'jcirc' => 309, //  latin small letter j with circumflex
		'Kcedil' => 310, //  latin capital letter k with cedilla
		'kcedil' => 311, //  latin small letter k with cedilla
		'kgreen' => 312, //  latin small letter kra
		'Lacute' => 313, //  latin capital letter l with acute
		'lacute' => 314, //  latin small letter l with acute
		'Lcedil' => 315, //  latin capital letter l with cedilla
		'lcedil' => 316, //  latin small letter l with cedilla
		'Lcaron' => 317, //  latin capital letter l with caron
		'lcaron' => 318, //  latin small letter l with caron
		'Lmidot' => 319, //  latin capital letter l with middle dot
		'lmidot' => 320, //  latin small letter l with middle dot
		'Lstrok' => 321, //  latin capital letter l with stroke
		'lstrok' => 322, //  latin small letter l with stroke
		'Nacute' => 323, //  latin capital letter n with acute
		'nacute' => 324, //  latin small letter n with acute
		'Ncedil' => 325, //  latin capital letter n with cedilla
		'ncedil' => 326, //  latin small letter n with cedilla
		'Ncaron' => 327, //  latin capital letter n with caron
		'ncaron' => 328, //  latin small letter n with caron
		'napos' => 329, //  latin small letter n preceded by apostrophe
		'ENG' => 330, //  latin capital letter eng
		'eng' => 331, //  latin small letter eng
		'Omacr' => 332, //  latin capital letter o with macron
		'omacr' => 333, //  latin small letter o with macron
		'Odblac' => 336, //  latin capital letter o with double acute
		'odblac' => 337, //  latin small letter o with double acute
		'OElig' => 338, //  latin capital ligature oe
		'oelig' => 339, //  latin small ligature oe
		'Racute' => 340, //  latin capital letter r with acute
		'racute' => 341, //  latin small letter r with acute
		'Rcedil' => 342, //  latin capital letter r with cedilla
		'rcedil' => 343, //  latin small letter r with cedilla
		'Rcaron' => 344, //  latin capital letter r with caron
		'rcaron' => 345, //  latin small letter r with caron
		'Sacute' => 346, //  latin capital letter s with acute
		'sacute' => 347, //  latin small letter s with acute
		'Scirc' => 348, //  latin capital letter s with circumflex
		'scirc' => 349, //  latin small letter s with circumflex
		'Scedil' => 350, //  latin capital letter s with cedilla
		'scedil' => 351, //  latin small letter s with cedilla
		'Scaron' => 352, //  latin capital letter s with caron
		'scaron' => 353, //  latin small letter s with caron
		'Tcedil' => 354, //  latin capital letter t with cedilla
		'tcedil' => 355, //  latin small letter t with cedilla
		'Tcaron' => 356, //  latin capital letter t with caron
		'tcaron' => 357, //  latin small letter t with caron
		'Tstrok' => 358, //  latin capital letter t with stroke
		'tstrok' => 359, //  latin small letter t with stroke
		'Utilde' => 360, //  latin capital letter u with tilde
		'utilde' => 361, //  latin small letter u with tilde
		'Umacr' => 362, //  latin capital letter u with macron
		'umacr' => 363, //  latin small letter u with macron
		'Ubreve' => 364, //  latin capital letter u with breve
		'ubreve' => 365, //  latin small letter u with breve
		'Uring' => 366, //  latin capital letter u with ring above
		'uring' => 367, //  latin small letter u with ring above
		'Udblac' => 368, //  latin capital letter u with double acute
		'udblac' => 369, //  latin small letter u with double acute
		'Uogon' => 370, //  latin capital letter u with ogonek
		'uogon' => 371, //  latin small letter u with ogonek
		'Wcirc' => 372, //  latin capital letter w with circumflex
		'wcirc' => 373, //  latin small letter w with circumflex
		'Ycirc' => 374, //  latin capital letter y with circumflex
		'ycirc' => 375, //  latin small letter y with circumflex
		'Yuml' => 376, //  latin capital letter y with diaeresis
		'Zacute' => 377, //  latin capital letter z with acute
		'zacute' => 378, //  latin small letter z with acute
		'Zdot' => 379, //  latin capital letter z with dot above
		'zdot' => 380, //  latin small letter z with dot above
		'Zcaron' => 381, //  latin capital letter z with caron
		'zcaron' => 382, //  latin small letter z with caron
		'fnof' => 402, //  latin small letter f with hook
		'imped' => 437, //  latin capital letter z with stroke
		'gacute' => 501, //  latin small letter g with acute
		'jmath' => 567, //  latin small letter dotless j
		'circ' => 710, //  modifier letter circumflex accent
		'caron' => 711, //  caron
		'Hacek' => 711,
		'breve' => 728, //  breve
		'Breve' => 728,
		'dot' => 729, //  dot above
		'DiacriticalDot' => 729,
		'ring' => 730, //  ring above
		'ogon' => 731, //  ogonek
		'tilde' => 732, //  small tilde
		'DiacriticalTilde' => 732,
		'dblac' => 733, //  double acute accent
		'DiacriticalDoubleAcute' => 733,
		'DownBreve' => 785, //  combining inverted breve
		'UnderBar' => 818, //  combining low line
		'Alpha' => 913, //  greek capital letter alpha
		'Beta' => 914, //  greek capital letter beta
		'Gamma' => 915, //  greek capital letter gamma
		'Delta' => 916, //  greek capital letter delta
		'Epsilon' => 917, //  greek capital letter epsilon
		'Zeta' => 918, //  greek capital letter zeta
		'Eta' => 919, //  greek capital letter eta
		'Theta' => 920, //  greek capital letter theta
		'Iota' => 921, //  greek capital letter iota
		'Kappa' => 922, //  greek capital letter kappa
		'Lambda' => 923, //  greek capital letter lamda
		'Mu' => 924, //  greek capital letter mu
		'Nu' => 925, //  greek capital letter nu
		'Xi' => 926, //  greek capital letter xi
		'Omicron' => 927, //  greek capital letter omicron
		'Pi' => 928, //  greek capital letter pi
		'Rho' => 929, //  greek capital letter rho
		'Sigma' => 931, //  greek capital letter sigma
		'Tau' => 932, //  greek capital letter tau
		'Upsilon' => 933, //  greek capital letter upsilon
		'Phi' => 934, //  greek capital letter phi
		'Chi' => 935, //  greek capital letter chi
		'Psi' => 936, //  greek capital letter psi
		'Omega' => 937, //  greek capital letter omega
		'alpha' => 945, //  greek small letter alpha
		'beta' => 946, //  greek small letter beta
		'gamma' => 947, //  greek small letter gamma
		'delta' => 948, //  greek small letter delta
		'epsiv' => 949, //  greek small letter epsilon
		'varepsilon' => 949,
		'epsilon' => 949,
		'zeta' => 950, //  greek small letter zeta
		'eta' => 951, //  greek small letter eta
		'theta' => 952, //  greek small letter theta
		'iota' => 953, //  greek small letter iota
		'kappa' => 954, //  greek small letter kappa
		'lambda' => 955, //  greek small letter lamda
		'mu' => 956, //  greek small letter mu
		'nu' => 957, //  greek small letter nu
		'xi' => 958, //  greek small letter xi
		'omicron' => 959, //  greek small letter omicron
		'pi' => 960, //  greek small letter pi
		'rho' => 961, //  greek small letter rho
		'sigmav' => 962, //  greek small letter final sigma
		'varsigma' => 962,
		'sigmaf' => 962,
		'sigma' => 963, //  greek small letter sigma
		'tau' => 964, //  greek small letter tau
		'upsi' => 965, //  greek small letter upsilon
		'upsilon' => 965,
		'phi' => 966, //  greek small letter phi
		'phiv' => 966,
		'varphi' => 966,
		'chi' => 967, //  greek small letter chi
		'psi' => 968, //  greek small letter psi
		'omega' => 969, //  greek small letter omega
		'thetav' => 977, //  greek theta symbol
		'vartheta' => 977,
		'thetasym' => 977,
		'Upsi' => 978, //  greek upsilon with hook symbol
		'upsih' => 978,
		'straightphi' => 981, //  greek phi symbol
		'piv' => 982, //  greek pi symbol
		'varpi' => 982,
		'Gammad' => 988, //  greek letter digamma
		'gammad' => 989, //  greek small letter digamma
		'digamma' => 989,
		'kappav' => 1008, //  greek kappa symbol
		'varkappa' => 1008,
		'rhov' => 1009, //  greek rho symbol
		'varrho' => 1009,
		'epsi' => 1013, //  greek lunate epsilon symbol
		'straightepsilon' => 1013,
		'bepsi' => 1014, //  greek reversed lunate epsilon symbol
		'backepsilon' => 1014,
		'IOcy' => 1025, //  cyrillic capital letter io
		'DJcy' => 1026, //  cyrillic capital letter dje
		'GJcy' => 1027, //  cyrillic capital letter gje
		'Jukcy' => 1028, //  cyrillic capital letter ukrainian ie
		'DScy' => 1029, //  cyrillic capital letter dze
		'Iukcy' => 1030, //  cyrillic capital letter byelorussian-ukrainian i
		'YIcy' => 1031, //  cyrillic capital letter yi
		'Jsercy' => 1032, //  cyrillic capital letter je
		'LJcy' => 1033, //  cyrillic capital letter lje
		'NJcy' => 1034, //  cyrillic capital letter nje
		'TSHcy' => 1035, //  cyrillic capital letter tshe
		'KJcy' => 1036, //  cyrillic capital letter kje
		'Ubrcy' => 1038, //  cyrillic capital letter short u
		'DZcy' => 1039, //  cyrillic capital letter dzhe
		'Acy' => 1040, //  cyrillic capital letter a
		'Bcy' => 1041, //  cyrillic capital letter be
		'Vcy' => 1042, //  cyrillic capital letter ve
		'Gcy' => 1043, //  cyrillic capital letter ghe
		'Dcy' => 1044, //  cyrillic capital letter de
		'IEcy' => 1045, //  cyrillic capital letter ie
		'ZHcy' => 1046, //  cyrillic capital letter zhe
		'Zcy' => 1047, //  cyrillic capital letter ze
		'Icy' => 1048, //  cyrillic capital letter i
		'Jcy' => 1049, //  cyrillic capital letter short i
		'Kcy' => 1050, //  cyrillic capital letter ka
		'Lcy' => 1051, //  cyrillic capital letter el
		'Mcy' => 1052, //  cyrillic capital letter em
		'Ncy' => 1053, //  cyrillic capital letter en
		'Ocy' => 1054, //  cyrillic capital letter o
		'Pcy' => 1055, //  cyrillic capital letter pe
		'Rcy' => 1056, //  cyrillic capital letter er
		'Scy' => 1057, //  cyrillic capital letter es
		'Tcy' => 1058, //  cyrillic capital letter te
		'Ucy' => 1059, //  cyrillic capital letter u
		'Fcy' => 1060, //  cyrillic capital letter ef
		'KHcy' => 1061, //  cyrillic capital letter ha
		'TScy' => 1062, //  cyrillic capital letter tse
		'CHcy' => 1063, //  cyrillic capital letter che
		'SHcy' => 1064, //  cyrillic capital letter sha
		'SHCHcy' => 1065, //  cyrillic capital letter shcha
		'HARDcy' => 1066, //  cyrillic capital letter hard sign
		'Ycy' => 1067, //  cyrillic capital letter yeru
		'SOFTcy' => 1068, //  cyrillic capital letter soft sign
		'Ecy' => 1069, //  cyrillic capital letter e
		'YUcy' => 1070, //  cyrillic capital letter yu
		'YAcy' => 1071, //  cyrillic capital letter ya
		'acy' => 1072, //  cyrillic small letter a
		'bcy' => 1073, //  cyrillic small letter be
		'vcy' => 1074, //  cyrillic small letter ve
		'gcy' => 1075, //  cyrillic small letter ghe
		'dcy' => 1076, //  cyrillic small letter de
		'iecy' => 1077, //  cyrillic small letter ie
		'zhcy' => 1078, //  cyrillic small letter zhe
		'zcy' => 1079, //  cyrillic small letter ze
		'icy' => 1080, //  cyrillic small letter i
		'jcy' => 1081, //  cyrillic small letter short i
		'kcy' => 1082, //  cyrillic small letter ka
		'lcy' => 1083, //  cyrillic small letter el
		'mcy' => 1084, //  cyrillic small letter em
		'ncy' => 1085, //  cyrillic small letter en
		'ocy' => 1086, //  cyrillic small letter o
		'pcy' => 1087, //  cyrillic small letter pe
		'rcy' => 1088, //  cyrillic small letter er
		'scy' => 1089, //  cyrillic small letter es
		'tcy' => 1090, //  cyrillic small letter te
		'ucy' => 1091, //  cyrillic small letter u
		'fcy' => 1092, //  cyrillic small letter ef
		'khcy' => 1093, //  cyrillic small letter ha
		'tscy' => 1094, //  cyrillic small letter tse
		'chcy' => 1095, //  cyrillic small letter che
		'shcy' => 1096, //  cyrillic small letter sha
		'shchcy' => 1097, //  cyrillic small letter shcha
		'hardcy' => 1098, //  cyrillic small letter hard sign
		'ycy' => 1099, //  cyrillic small letter yeru
		'softcy' => 1100, //  cyrillic small letter soft sign
		'ecy' => 1101, //  cyrillic small letter e
		'yucy' => 1102, //  cyrillic small letter yu
		'yacy' => 1103, //  cyrillic small letter ya
		'iocy' => 1105, //  cyrillic small letter io
		'djcy' => 1106, //  cyrillic small letter dje
		'gjcy' => 1107, //  cyrillic small letter gje
		'jukcy' => 1108, //  cyrillic small letter ukrainian ie
		'dscy' => 1109, //  cyrillic small letter dze
		'iukcy' => 1110, //  cyrillic small letter byelorussian-ukrainian i
		'yicy' => 1111, //  cyrillic small letter yi
		'jsercy' => 1112, //  cyrillic small letter je
		'ljcy' => 1113, //  cyrillic small letter lje
		'njcy' => 1114, //  cyrillic small letter nje
		'tshcy' => 1115, //  cyrillic small letter tshe
		'kjcy' => 1116, //  cyrillic small letter kje
		'ubrcy' => 1118, //  cyrillic small letter short u
		'dzcy' => 1119, //  cyrillic small letter dzhe
		'ensp' => 8194, //  en space
		'emsp' => 8195, //  em space
		'emsp13' => 8196, //  three-per-em space
		'emsp14' => 8197, //  four-per-em space
		'numsp' => 8199, //  figure space
		'puncsp' => 8200, //  punctuation space
		'thinsp' => 8201, //  thin space
		'ThinSpace' => 8201,
		'hairsp' => 8202, //  hair space
		'VeryThinSpace' => 8202,
		'ZeroWidthSpace' => 8203, //  zero width space
		'NegativeVeryThinSpace' => 8203,
		'NegativeThinSpace' => 8203,
		'NegativeMediumSpace' => 8203,
		'NegativeThickSpace' => 8203,
		'zwnj' => 8204, //  zero width non-joiner
		'zwj' => 8205, //  zero width joiner
		'lrm' => 8206, //  left-to-right mark
		'rlm' => 8207, //  right-to-left mark
		'hyphen' => 8208, //  hyphen
		'dash' => 8208,
		'ndash' => 8211, //  en dash
		'mdash' => 8212, //  em dash
		'horbar' => 8213, //  horizontal bar
		'Verbar' => 8214, //  double vertical line
		'Vert' => 8214,
		'lsquo' => 8216, //  left single quotation mark
		'OpenCurlyQuote' => 8216,
		'rsquo' => 8217, //  right single quotation mark
		'rsquor' => 8217,
		'CloseCurlyQuote' => 8217,
		'lsquor' => 8218, //  single low-9 quotation mark
		'sbquo' => 8218,
		'ldquo' => 8220, //  left double quotation mark
		'OpenCurlyDoubleQuote' => 8220,
		'rdquo' => 8221, //  right double quotation mark
		'rdquor' => 8221,
		'CloseCurlyDoubleQuote' => 8221,
		'ldquor' => 8222, //  double low-9 quotation mark
		'bdquo' => 8222,
		'dagger' => 8224, //  dagger
		'Dagger' => 8225, //  double dagger
		'ddagger' => 8225,
		'bull' => 8226, //  bullet
		'bullet' => 8226,
		'nldr' => 8229, //  two dot leader
		'hellip' => 8230, //  horizontal ellipsis
		'mldr' => 8230,
		'permil' => 8240, //  per mille sign
		'pertenk' => 8241, //  per ten thousand sign
		'prime' => 8242, //  prime
		'Prime' => 8243, //  double prime
		'tprime' => 8244, //  triple prime
		'bprime' => 8245, //  reversed prime
		'backprime' => 8245,
		'lsaquo' => 8249, //  single left-pointing angle quotation mark
		'rsaquo' => 8250, //  single right-pointing angle quotation mark
		'oline' => 8254, //  overline
		'caret' => 8257, //  caret insertion point
		'hybull' => 8259, //  hyphen bullet
		'frasl' => 8260, //  fraction slash
		'bsemi' => 8271, //  reversed semicolon
		'qprime' => 8279, //  quadruple prime
		'MediumSpace' => 8287, //  medium mathematical space
		'NoBreak' => 8288, //  word joiner
		'ApplyFunction' => 8289, //  function application
		'af' => 8289,
		'InvisibleTimes' => 8290, //  invisible times
		'it' => 8290,
		'InvisibleComma' => 8291, //  invisible separator
		'ic' => 8291,
		'euro' => 8364, //  euro sign
		'tdot' => 8411, //  combining three dots above
		'TripleDot' => 8411,
		'DotDot' => 8412, //  combining four dots above
		'Copf' => 8450, //  double-struck capital c
		'complexes' => 8450,
		'incare' => 8453, //  care of
		'gscr' => 8458, //  script small g
		'hamilt' => 8459, //  script capital h
		'HilbertSpace' => 8459,
		'Hscr' => 8459,
		'Hfr' => 8460, //  black-letter capital h
		'Poincareplane' => 8460,
		'quaternions' => 8461, //  double-struck capital h
		'Hopf' => 8461,
		'planckh' => 8462, //  planck constant
		'planck' => 8463, //  planck constant over two pi
		'hbar' => 8463,
		'plankv' => 8463,
		'hslash' => 8463,
		'Iscr' => 8464, //  script capital i
		'imagline' => 8464,
		'image' => 8465, //  black-letter capital i
		'Im' => 8465,
		'imagpart' => 8465,
		'Ifr' => 8465,
		'Lscr' => 8466, //  script capital l
		'lagran' => 8466,
		'Laplacetrf' => 8466,
		'ell' => 8467, //  script small l
		'Nopf' => 8469, //  double-struck capital n
		'naturals' => 8469,
		'numero' => 8470, //  numero sign
		'copysr' => 8471, //  sound recording copyright
		'weierp' => 8472, //  script capital p
		'wp' => 8472,
		'Popf' => 8473, //  double-struck capital p
		'primes' => 8473,
		'rationals' => 8474, //  double-struck capital q
		'Qopf' => 8474,
		'Rscr' => 8475, //  script capital r
		'realine' => 8475,
		'real' => 8476, //  black-letter capital r
		'Re' => 8476,
		'realpart' => 8476,
		'Rfr' => 8476,
		'reals' => 8477, //  double-struck capital r
		'Ropf' => 8477,
		'rx' => 8478, //  prescription take
		'trade' => 8482, //  trade mark sign
		'TRADE' => 8482,
		'integers' => 8484, //  double-struck capital z
		'Zopf' => 8484,
		'ohm' => 8486, //  ohm sign
		'mho' => 8487, //  inverted ohm sign
		'Zfr' => 8488, //  black-letter capital z
		'zeetrf' => 8488,
		'iiota' => 8489, //  turned greek small letter iota
		'angst' => 8491, //  angstrom sign
		'bernou' => 8492, //  script capital b
		'Bernoullis' => 8492,
		'Bscr' => 8492,
		'Cfr' => 8493, //  black-letter capital c
		'Cayleys' => 8493,
		'escr' => 8495, //  script small e
		'Escr' => 8496, //  script capital e
		'expectation' => 8496,
		'Fscr' => 8497, //  script capital f
		'Fouriertrf' => 8497,
		'phmmat' => 8499, //  script capital m
		'Mellintrf' => 8499,
		'Mscr' => 8499,
		'order' => 8500, //  script small o
		'orderof' => 8500,
		'oscr' => 8500,
		'alefsym' => 8501, //  alef symbol
		'aleph' => 8501,
		'beth' => 8502, //  bet symbol
		'gimel' => 8503, //  gimel symbol
		'daleth' => 8504, //  dalet symbol
		'CapitalDifferentialD' => 8517, //  double-struck italic capital d
		'DD' => 8517,
		'DifferentialD' => 8518, //  double-struck italic small d
		'dd' => 8518,
		'ExponentialE' => 8519, //  double-struck italic small e
		'exponentiale' => 8519,
		'ee' => 8519,
		'ImaginaryI' => 8520, //  double-struck italic small i
		'ii' => 8520,
		'frac13' => 8531, //  vulgar fraction one third
		'frac23' => 8532, //  vulgar fraction two thirds
		'frac15' => 8533, //  vulgar fraction one fifth
		'frac25' => 8534, //  vulgar fraction two fifths
		'frac35' => 8535, //  vulgar fraction three fifths
		'frac45' => 8536, //  vulgar fraction four fifths
		'frac16' => 8537, //  vulgar fraction one sixth
		'frac56' => 8538, //  vulgar fraction five sixths
		'frac18' => 8539, //  vulgar fraction one eighth
		'frac38' => 8540, //  vulgar fraction three eighths
		'frac58' => 8541, //  vulgar fraction five eighths
		'frac78' => 8542, //  vulgar fraction seven eighths
		'larr' => 8592, //  leftwards arrow
		'leftarrow' => 8592,
		'LeftArrow' => 8592,
		'slarr' => 8592,
		'ShortLeftArrow' => 8592,
		'uarr' => 8593, //  upwards arrow
		'uparrow' => 8593,
		'UpArrow' => 8593,
		'ShortUpArrow' => 8593,
		'rarr' => 8594, //  rightwards arrow
		'rightarrow' => 8594,
		'RightArrow' => 8594,
		'srarr' => 8594,
		'ShortRightArrow' => 8594,
		'darr' => 8595, //  downwards arrow
		'downarrow' => 8595,
		'DownArrow' => 8595,
		'ShortDownArrow' => 8595,
		'harr' => 8596, //  left right arrow
		'leftrightarrow' => 8596,
		'LeftRightArrow' => 8596,
		'varr' => 8597, //  up down arrow
		'updownarrow' => 8597,
		'UpDownArrow' => 8597,
		'nwarr' => 8598, //  north west arrow
		'UpperLeftArrow' => 8598,
		'nwarrow' => 8598,
		'nearr' => 8599, //  north east arrow
		'UpperRightArrow' => 8599,
		'nearrow' => 8599,
		'searr' => 8600, //  south east arrow
		'searrow' => 8600,
		'LowerRightArrow' => 8600,
		'swarr' => 8601, //  south west arrow
		'swarrow' => 8601,
		'LowerLeftArrow' => 8601,
		'nlarr' => 8602, //  leftwards arrow with stroke
		'nleftarrow' => 8602,
		'nrarr' => 8603, //  rightwards arrow with stroke
		'nrightarrow' => 8603,
		'rarrw' => 8605, //  rightwards wave arrow
		'rightsquigarrow' => 8605,
		'Larr' => 8606, //  leftwards two headed arrow
		'twoheadleftarrow' => 8606,
		'Uarr' => 8607, //  upwards two headed arrow
		'Rarr' => 8608, //  rightwards two headed arrow
		'twoheadrightarrow' => 8608,
		'Darr' => 8609, //  downwards two headed arrow
		'larrtl' => 8610, //  leftwards arrow with tail
		'leftarrowtail' => 8610,
		'rarrtl' => 8611, //  rightwards arrow with tail
		'rightarrowtail' => 8611,
		'LeftTeeArrow' => 8612, //  leftwards arrow from bar
		'mapstoleft' => 8612,
		'UpTeeArrow' => 8613, //  upwards arrow from bar
		'mapstoup' => 8613,
		'map' => 8614, //  rightwards arrow from bar
		'RightTeeArrow' => 8614,
		'mapsto' => 8614,
		'DownTeeArrow' => 8615, //  downwards arrow from bar
		'mapstodown' => 8615,
		'larrhk' => 8617, //  leftwards arrow with hook
		'hookleftarrow' => 8617,
		'rarrhk' => 8618, //  rightwards arrow with hook
		'hookrightarrow' => 8618,
		'larrlp' => 8619, //  leftwards arrow with loop
		'looparrowleft' => 8619,
		'rarrlp' => 8620, //  rightwards arrow with loop
		'looparrowright' => 8620,
		'harrw' => 8621, //  left right wave arrow
		'leftrightsquigarrow' => 8621,
		'nharr' => 8622, //  left right arrow with stroke
		'nleftrightarrow' => 8622,
		'lsh' => 8624, //  upwards arrow with tip leftwards
		'Lsh' => 8624,
		'rsh' => 8625, //  upwards arrow with tip rightwards
		'Rsh' => 8625,
		'ldsh' => 8626, //  downwards arrow with tip leftwards
		'rdsh' => 8627, //  downwards arrow with tip rightwards
		'crarr' => 8629, //  downwards arrow with corner leftwards
		'cularr' => 8630, //  anticlockwise top semicircle arrow
		'curvearrowleft' => 8630,
		'curarr' => 8631, //  clockwise top semicircle arrow
		'curvearrowright' => 8631,
		'olarr' => 8634, //  anticlockwise open circle arrow
		'circlearrowleft' => 8634,
		'orarr' => 8635, //  clockwise open circle arrow
		'circlearrowright' => 8635,
		'lharu' => 8636, //  leftwards harpoon with barb upwards
		'LeftVector' => 8636,
		'leftharpoonup' => 8636,
		'lhard' => 8637, //  leftwards harpoon with barb downwards
		'leftharpoondown' => 8637,
		'DownLeftVector' => 8637,
		'uharr' => 8638, //  upwards harpoon with barb rightwards
		'upharpoonright' => 8638,
		'RightUpVector' => 8638,
		'uharl' => 8639, //  upwards harpoon with barb leftwards
		'upharpoonleft' => 8639,
		'LeftUpVector' => 8639,
		'rharu' => 8640, //  rightwards harpoon with barb upwards
		'RightVector' => 8640,
		'rightharpoonup' => 8640,
		'rhard' => 8641, //  rightwards harpoon with barb downwards
		'rightharpoondown' => 8641,
		'DownRightVector' => 8641,
		'dharr' => 8642, //  downwards harpoon with barb rightwards
		'RightDownVector' => 8642,
		'downharpoonright' => 8642,
		'dharl' => 8643, //  downwards harpoon with barb leftwards
		'LeftDownVector' => 8643,
		'downharpoonleft' => 8643,
		'rlarr' => 8644, //  rightwards arrow over leftwards arrow
		'rightleftarrows' => 8644,
		'RightArrowLeftArrow' => 8644,
		'udarr' => 8645, //  upwards arrow leftwards of downwards arrow
		'UpArrowDownArrow' => 8645,
		'lrarr' => 8646, //  leftwards arrow over rightwards arrow
		'leftrightarrows' => 8646,
		'LeftArrowRightArrow' => 8646,
		'llarr' => 8647, //  leftwards paired arrows
		'leftleftarrows' => 8647,
		'uuarr' => 8648, //  upwards paired arrows
		'upuparrows' => 8648,
		'rrarr' => 8649, //  rightwards paired arrows
		'rightrightarrows' => 8649,
		'ddarr' => 8650, //  downwards paired arrows
		'downdownarrows' => 8650,
		'lrhar' => 8651, //  leftwards harpoon over rightwards harpoon
		'ReverseEquilibrium' => 8651,
		'leftrightharpoons' => 8651,
		'rlhar' => 8652, //  rightwards harpoon over leftwards harpoon
		'rightleftharpoons' => 8652,
		'Equilibrium' => 8652,
		'nlArr' => 8653, //  leftwards double arrow with stroke
		'nLeftarrow' => 8653,
		'nhArr' => 8654, //  left right double arrow with stroke
		'nLeftrightarrow' => 8654,
		'nrArr' => 8655, //  rightwards double arrow with stroke
		'nRightarrow' => 8655,
		'lArr' => 8656, //  leftwards double arrow
		'Leftarrow' => 8656,
		'DoubleLeftArrow' => 8656,
		'uArr' => 8657, //  upwards double arrow
		'Uparrow' => 8657,
		'DoubleUpArrow' => 8657,
		'rArr' => 8658, //  rightwards double arrow
		'Rightarrow' => 8658,
		'Implies' => 8658,
		'DoubleRightArrow' => 8658,
		'dArr' => 8659, //  downwards double arrow
		'Downarrow' => 8659,
		'DoubleDownArrow' => 8659,
		'hArr' => 8660, //  left right double arrow
		'Leftrightarrow' => 8660,
		'DoubleLeftRightArrow' => 8660,
		'iff' => 8660,
		'vArr' => 8661, //  up down double arrow
		'Updownarrow' => 8661,
		'DoubleUpDownArrow' => 8661,
		'nwArr' => 8662, //  north west double arrow
		'neArr' => 8663, //  north east double arrow
		'seArr' => 8664, //  south east double arrow
		'swArr' => 8665, //  south west double arrow
		'lAarr' => 8666, //  leftwards triple arrow
		'Lleftarrow' => 8666,
		'rAarr' => 8667, //  rightwards triple arrow
		'Rrightarrow' => 8667,
		'zigrarr' => 8669, //  rightwards squiggle arrow
		'larrb' => 8676, //  leftwards arrow to bar
		'LeftArrowBar' => 8676,
		'rarrb' => 8677, //  rightwards arrow to bar
		'RightArrowBar' => 8677,
		'duarr' => 8693, //  downwards arrow leftwards of upwards arrow
		'DownArrowUpArrow' => 8693,
		'loarr' => 8701, //  leftwards open-headed arrow
		'roarr' => 8702, //  rightwards open-headed arrow
		'hoarr' => 8703, //  left right open-headed arrow
		'forall' => 8704, //  for all
		'ForAll' => 8704,
		'comp' => 8705, //  complement
		'complement' => 8705,
		'part' => 8706, //  partial differential
		'PartialD' => 8706,
		'exist' => 8707, //  there exists
		'Exists' => 8707,
		'nexist' => 8708, //  there does not exist
		'NotExists' => 8708,
		'nexists' => 8708,
		'empty' => 8709, //  empty set
		'emptyset' => 8709,
		'emptyv' => 8709,
		'varnothing' => 8709,
		'nabla' => 8711, //  nabla
		'Del' => 8711,
		'isin' => 8712, //  element of
		'isinv' => 8712,
		'Element' => 8712,
		'in' => 8712,
		'notin' => 8713, //  not an element of
		'NotElement' => 8713,
		'notinva' => 8713,
		'niv' => 8715, //  contains as member
		'ReverseElement' => 8715,
		'ni' => 8715,
		'SuchThat' => 8715,
		'notni' => 8716, //  does not contain as member
		'notniva' => 8716,
		'NotReverseElement' => 8716,
		'prod' => 8719, //  n-ary product
		'Product' => 8719,
		'coprod' => 8720, //  n-ary coproduct
		'Coproduct' => 8720,
		'sum' => 8721, //  n-ary summation
		'Sum' => 8721,
		'minus' => 8722, //  minus sign
		'mnplus' => 8723, //  minus-or-plus sign
		'mp' => 8723,
		'MinusPlus' => 8723,
		'plusdo' => 8724, //  dot plus
		'dotplus' => 8724,
		'setmn' => 8726, //  set minus
		'setminus' => 8726,
		'Backslash' => 8726,
		'ssetmn' => 8726,
		'smallsetminus' => 8726,
		'lowast' => 8727, //  asterisk operator
		'compfn' => 8728, //  ring operator
		'SmallCircle' => 8728,
		'radic' => 8730, //  square root
		'Sqrt' => 8730,
		'prop' => 8733, //  proportional to
		'propto' => 8733,
		'Proportional' => 8733,
		'vprop' => 8733,
		'varpropto' => 8733,
		'infin' => 8734, //  infinity
		'angrt' => 8735, //  right angle
		'ang' => 8736, //  angle
		'angle' => 8736,
		'angmsd' => 8737, //  measured angle
		'measuredangle' => 8737,
		'angsph' => 8738, //  spherical angle
		'mid' => 8739, //  divides
		'VerticalBar' => 8739,
		'smid' => 8739,
		'shortmid' => 8739,
		'nmid' => 8740, //  does not divide
		'NotVerticalBar' => 8740,
		'nsmid' => 8740,
		'nshortmid' => 8740,
		'par' => 8741, //  parallel to
		'parallel' => 8741,
		'DoubleVerticalBar' => 8741,
		'spar' => 8741,
		'shortparallel' => 8741,
		'npar' => 8742, //  not parallel to
		'nparallel' => 8742,
		'NotDoubleVerticalBar' => 8742,
		'nspar' => 8742,
		'nshortparallel' => 8742,
		'and' => 8743, //  logical and
		'wedge' => 8743,
		'or' => 8744, //  logical or
		'vee' => 8744,
		'cap' => 8745, //  intersection
		'cup' => 8746, //  union
		'int' => 8747, //  integral
		'Integral' => 8747,
		'Int' => 8748, //  double integral
		'tint' => 8749, //  triple integral
		'iiint' => 8749,
		'conint' => 8750, //  contour integral
		'oint' => 8750,
		'ContourIntegral' => 8750,
		'Conint' => 8751, //  surface integral
		'DoubleContourIntegral' => 8751,
		'Cconint' => 8752, //  volume integral
		'cwint' => 8753, //  clockwise integral
		'cwconint' => 8754, //  clockwise contour integral
		'ClockwiseContourIntegral' => 8754,
		'awconint' => 8755, //  anticlockwise contour integral
		'CounterClockwiseContourIntegral' => 8755,
		'there4' => 8756, //  therefore
		'therefore' => 8756,
		'Therefore' => 8756,
		'becaus' => 8757, //  because
		'because' => 8757,
		'Because' => 8757,
		'ratio' => 8758, //  ratio
		'Colon' => 8759, //  proportion
		'Proportion' => 8759,
		'minusd' => 8760, //  dot minus
		'dotminus' => 8760,
		'mDDot' => 8762, //  geometric proportion
		'homtht' => 8763, //  homothetic
		'sim' => 8764, //  tilde operator
		'Tilde' => 8764,
		'thksim' => 8764,
		'thicksim' => 8764,
		'bsim' => 8765, //  reversed tilde
		'backsim' => 8765,
		'ac' => 8766, //  inverted lazy s
		'mstpos' => 8766,
		'acd' => 8767, //  sine wave
		'wreath' => 8768, //  wreath product
		'VerticalTilde' => 8768,
		'wr' => 8768,
		'nsim' => 8769, //  not tilde
		'NotTilde' => 8769,
		'esim' => 8770, //  minus tilde
		'EqualTilde' => 8770,
		'eqsim' => 8770,
		'sime' => 8771, //  asymptotically equal to
		'TildeEqual' => 8771,
		'simeq' => 8771,
		'nsime' => 8772, //  not asymptotically equal to
		'nsimeq' => 8772,
		'NotTildeEqual' => 8772,
		'cong' => 8773, //  approximately equal to
		'TildeFullEqual' => 8773,
		'simne' => 8774, //  approximately but not actually equal to
		'ncong' => 8775, //  neither approximately nor actually equal to
		'NotTildeFullEqual' => 8775,
		'asymp' => 8776, //  almost equal to
		'ap' => 8776,
		'TildeTilde' => 8776,
		'approx' => 8776,
		'thkap' => 8776,
		'thickapprox' => 8776,
		'nap' => 8777, //  not almost equal to
		'NotTildeTilde' => 8777,
		'napprox' => 8777,
		'ape' => 8778, //  almost equal or equal to
		'approxeq' => 8778,
		'apid' => 8779, //  triple tilde
		'bcong' => 8780, //  all equal to
		'backcong' => 8780,
		'asympeq' => 8781, //  equivalent to
		'CupCap' => 8781,
		'bump' => 8782, //  geometrically equivalent to
		'HumpDownHump' => 8782,
		'Bumpeq' => 8782,
		'bumpe' => 8783, //  difference between
		'HumpEqual' => 8783,
		'bumpeq' => 8783,
		'esdot' => 8784, //  approaches the limit
		'DotEqual' => 8784,
		'doteq' => 8784,
		'eDot' => 8785, //  geometrically equal to
		'doteqdot' => 8785,
		'efDot' => 8786, //  approximately equal to or the image of
		'fallingdotseq' => 8786,
		'erDot' => 8787, //  image of or approximately equal to
		'risingdotseq' => 8787,
		'colone' => 8788, //  colon equals
		'coloneq' => 8788,
		'Assign' => 8788,
		'ecolon' => 8789, //  equals colon
		'eqcolon' => 8789,
		'ecir' => 8790, //  ring in equal to
		'eqcirc' => 8790,
		'cire' => 8791, //  ring equal to
		'circeq' => 8791,
		'wedgeq' => 8793, //  estimates
		'veeeq' => 8794, //  equiangular to
		'trie' => 8796, //  delta equal to
		'triangleq' => 8796,
		'equest' => 8799, //  questioned equal to
		'questeq' => 8799,
		'ne' => 8800, //  not equal to
		'NotEqual' => 8800,
		'equiv' => 8801, //  identical to
		'Congruent' => 8801,
		'nequiv' => 8802, //  not identical to
		'NotCongruent' => 8802,
		'le' => 8804, //  less-than or equal to
		'leq' => 8804,
		'ge' => 8805, //  greater-than or equal to
		'GreaterEqual' => 8805,
		'geq' => 8805,
		'lE' => 8806, //  less-than over equal to
		'LessFullEqual' => 8806,
		'leqq' => 8806,
		'gE' => 8807, //  greater-than over equal to
		'GreaterFullEqual' => 8807,
		'geqq' => 8807,
		'lnE' => 8808, //  less-than but not equal to
		'lneqq' => 8808,
		'gnE' => 8809, //  greater-than but not equal to
		'gneqq' => 8809,
		'Lt' => 8810, //  much less-than
		'NestedLessLess' => 8810,
		'll' => 8810,
		'Gt' => 8811, //  much greater-than
		'NestedGreaterGreater' => 8811,
		'gg' => 8811,
		'twixt' => 8812, //  between
		'between' => 8812,
		'NotCupCap' => 8813, //  not equivalent to
		'nlt' => 8814, //  not less-than
		'NotLess' => 8814,
		'nless' => 8814,
		'ngt' => 8815, //  not greater-than
		'NotGreater' => 8815,
		'ngtr' => 8815,
		'nle' => 8816, //  neither less-than nor equal to
		'NotLessEqual' => 8816,
		'nleq' => 8816,
		'nge' => 8817, //  neither greater-than nor equal to
		'NotGreaterEqual' => 8817,
		'ngeq' => 8817,
		'lsim' => 8818, //  less-than or equivalent to
		'LessTilde' => 8818,
		'lesssim' => 8818,
		'gsim' => 8819, //  greater-than or equivalent to
		'gtrsim' => 8819,
		'GreaterTilde' => 8819,
		'nlsim' => 8820, //  neither less-than nor equivalent to
		'NotLessTilde' => 8820,
		'ngsim' => 8821, //  neither greater-than nor equivalent to
		'NotGreaterTilde' => 8821,
		'lg' => 8822, //  less-than or greater-than
		'lessgtr' => 8822,
		'LessGreater' => 8822,
		'gl' => 8823, //  greater-than or less-than
		'gtrless' => 8823,
		'GreaterLess' => 8823,
		'ntlg' => 8824, //  neither less-than nor greater-than
		'NotLessGreater' => 8824,
		'ntgl' => 8825, //  neither greater-than nor less-than
		'NotGreaterLess' => 8825,
		'pr' => 8826, //  precedes
		'Precedes' => 8826,
		'prec' => 8826,
		'sc' => 8827, //  succeeds
		'Succeeds' => 8827,
		'succ' => 8827,
		'prcue' => 8828, //  precedes or equal to
		'PrecedesSlantEqual' => 8828,
		'preccurlyeq' => 8828,
		'sccue' => 8829, //  succeeds or equal to
		'SucceedsSlantEqual' => 8829,
		'succcurlyeq' => 8829,
		'prsim' => 8830, //  precedes or equivalent to
		'precsim' => 8830,
		'PrecedesTilde' => 8830,
		'scsim' => 8831, //  succeeds or equivalent to
		'succsim' => 8831,
		'SucceedsTilde' => 8831,
		'npr' => 8832, //  does not precede
		'nprec' => 8832,
		'NotPrecedes' => 8832,
		'nsc' => 8833, //  does not succeed
		'nsucc' => 8833,
		'NotSucceeds' => 8833,
		'sub' => 8834, //  subset of
		'subset' => 8834,
		'sup' => 8835, //  superset of
		'supset' => 8835,
		'Superset' => 8835,
		'nsub' => 8836, //  not a subset of
		'nsup' => 8837, //  not a superset of
		'sube' => 8838, //  subset of or equal to
		'SubsetEqual' => 8838,
		'subseteq' => 8838,
		'supe' => 8839, //  superset of or equal to
		'supseteq' => 8839,
		'SupersetEqual' => 8839,
		'nsube' => 8840, //  neither a subset of nor equal to
		'nsubseteq' => 8840,
		'NotSubsetEqual' => 8840,
		'nsupe' => 8841, //  neither a superset of nor equal to
		'nsupseteq' => 8841,
		'NotSupersetEqual' => 8841,
		'subne' => 8842, //  subset of with not equal to
		'subsetneq' => 8842,
		'supne' => 8843, //  superset of with not equal to
		'supsetneq' => 8843,
		'cupdot' => 8845, //  multiset multiplication
		'uplus' => 8846, //  multiset union
		'UnionPlus' => 8846,
		'sqsub' => 8847, //  square image of
		'SquareSubset' => 8847,
		'sqsubset' => 8847,
		'sqsup' => 8848, //  square original of
		'SquareSuperset' => 8848,
		'sqsupset' => 8848,
		'sqsube' => 8849, //  square image of or equal to
		'SquareSubsetEqual' => 8849,
		'sqsubseteq' => 8849,
		'sqsupe' => 8850, //  square original of or equal to
		'SquareSupersetEqual' => 8850,
		'sqsupseteq' => 8850,
		'sqcap' => 8851, //  square cap
		'SquareIntersection' => 8851,
		'sqcup' => 8852, //  square cup
		'SquareUnion' => 8852,
		'oplus' => 8853, //  circled plus
		'CirclePlus' => 8853,
		'ominus' => 8854, //  circled minus
		'CircleMinus' => 8854,
		'otimes' => 8855, //  circled times
		'CircleTimes' => 8855,
		'osol' => 8856, //  circled division slash
		'odot' => 8857, //  circled dot operator
		'CircleDot' => 8857,
		'ocir' => 8858, //  circled ring operator
		'circledcirc' => 8858,
		'oast' => 8859, //  circled asterisk operator
		'circledast' => 8859,
		'odash' => 8861, //  circled dash
		'circleddash' => 8861,
		'plusb' => 8862, //  squared plus
		'boxplus' => 8862,
		'minusb' => 8863, //  squared minus
		'boxminus' => 8863,
		'timesb' => 8864, //  squared times
		'boxtimes' => 8864,
		'sdotb' => 8865, //  squared dot operator
		'dotsquare' => 8865,
		'vdash' => 8866, //  right tack
		'RightTee' => 8866,
		'dashv' => 8867, //  left tack
		'LeftTee' => 8867,
		'top' => 8868, //  down tack
		'DownTee' => 8868,
		'bottom' => 8869, //  up tack
		'bot' => 8869,
		'perp' => 8869,
		'UpTee' => 8869,
		'models' => 8871, //  models
		'vDash' => 8872, //  true
		'DoubleRightTee' => 8872,
		'Vdash' => 8873, //  forces
		'Vvdash' => 8874, //  triple vertical bar right turnstile
		'VDash' => 8875, //  double vertical bar double right turnstile
		'nvdash' => 8876, //  does not prove
		'nvDash' => 8877, //  not true
		'nVdash' => 8878, //  does not force
		'nVDash' => 8879, //  negated double vertical bar double right turnstile
		'prurel' => 8880, //  precedes under relation
		'vltri' => 8882, //  normal subgroup of
		'vartriangleleft' => 8882,
		'LeftTriangle' => 8882,
		'vrtri' => 8883, //  contains as normal subgroup
		'vartriangleright' => 8883,
		'RightTriangle' => 8883,
		'ltrie' => 8884, //  normal subgroup of or equal to
		'trianglelefteq' => 8884,
		'LeftTriangleEqual' => 8884,
		'rtrie' => 8885, //  contains as normal subgroup or equal to
		'trianglerighteq' => 8885,
		'RightTriangleEqual' => 8885,
		'origof' => 8886, //  original of
		'imof' => 8887, //  image of
		'mumap' => 8888, //  multimap
		'multimap' => 8888,
		'hercon' => 8889, //  hermitian conjugate matrix
		'intcal' => 8890, //  intercalate
		'intercal' => 8890,
		'veebar' => 8891, //  xor
		'barvee' => 8893, //  nor
		'angrtvb' => 8894, //  right angle with arc
		'lrtri' => 8895, //  right triangle
		'xwedge' => 8896, //  n-ary logical and
		'Wedge' => 8896,
		'bigwedge' => 8896,
		'xvee' => 8897, //  n-ary logical or
		'Vee' => 8897,
		'bigvee' => 8897,
		'xcap' => 8898, //  n-ary intersection
		'Intersection' => 8898,
		'bigcap' => 8898,
		'xcup' => 8899, //  n-ary union
		'Union' => 8899,
		'bigcup' => 8899,
		'diam' => 8900, //  diamond operator
		'diamond' => 8900,
		'Diamond' => 8900,
		'sdot' => 8901, //  dot operator
		'sstarf' => 8902, //  star operator
		'Star' => 8902,
		'divonx' => 8903, //  division times
		'divideontimes' => 8903,
		'bowtie' => 8904, //  bowtie
		'ltimes' => 8905, //  left normal factor semidirect product
		'rtimes' => 8906, //  right normal factor semidirect product
		'lthree' => 8907, //  left semidirect product
		'leftthreetimes' => 8907,
		'rthree' => 8908, //  right semidirect product
		'rightthreetimes' => 8908,
		'bsime' => 8909, //  reversed tilde equals
		'backsimeq' => 8909,
		'cuvee' => 8910, //  curly logical or
		'curlyvee' => 8910,
		'cuwed' => 8911, //  curly logical and
		'curlywedge' => 8911,
		'Sub' => 8912, //  double subset
		'Subset' => 8912,
		'Sup' => 8913, //  double superset
		'Supset' => 8913,
		'Cap' => 8914, //  double intersection
		'Cup' => 8915, //  double union
		'fork' => 8916, //  pitchfork
		'pitchfork' => 8916,
		'epar' => 8917, //  equal and parallel to
		'ltdot' => 8918, //  less-than with dot
		'lessdot' => 8918,
		'gtdot' => 8919, //  greater-than with dot
		'gtrdot' => 8919,
		'Ll' => 8920, //  very much less-than
		'Gg' => 8921, //  very much greater-than
		'ggg' => 8921,
		'leg' => 8922, //  less-than equal to or greater-than
		'LessEqualGreater' => 8922,
		'lesseqgtr' => 8922,
		'gel' => 8923, //  greater-than equal to or less-than
		'gtreqless' => 8923,
		'GreaterEqualLess' => 8923,
		'cuepr' => 8926, //  equal to or precedes
		'curlyeqprec' => 8926,
		'cuesc' => 8927, //  equal to or succeeds
		'curlyeqsucc' => 8927,
		'nprcue' => 8928, //  does not precede or equal
		'NotPrecedesSlantEqual' => 8928,
		'nsccue' => 8929, //  does not succeed or equal
		'NotSucceedsSlantEqual' => 8929,
		'nsqsube' => 8930, //  not square image of or equal to
		'NotSquareSubsetEqual' => 8930,
		'nsqsupe' => 8931, //  not square original of or equal to
		'NotSquareSupersetEqual' => 8931,
		'lnsim' => 8934, //  less-than but not equivalent to
		'gnsim' => 8935, //  greater-than but not equivalent to
		'prnsim' => 8936, //  precedes but not equivalent to
		'precnsim' => 8936,
		'scnsim' => 8937, //  succeeds but not equivalent to
		'succnsim' => 8937,
		'nltri' => 8938, //  not normal subgroup of
		'ntriangleleft' => 8938,
		'NotLeftTriangle' => 8938,
		'nrtri' => 8939, //  does not contain as normal subgroup
		'ntriangleright' => 8939,
		'NotRightTriangle' => 8939,
		'nltrie' => 8940, //  not normal subgroup of or equal to
		'ntrianglelefteq' => 8940,
		'NotLeftTriangleEqual' => 8940,
		'nrtrie' => 8941, //  does not contain as normal subgroup or equal
		'ntrianglerighteq' => 8941,
		'NotRightTriangleEqual' => 8941,
		'vellip' => 8942, //  vertical ellipsis
		'ctdot' => 8943, //  midline horizontal ellipsis
		'utdot' => 8944, //  up right diagonal ellipsis
		'dtdot' => 8945, //  down right diagonal ellipsis
		'disin' => 8946, //  element of with long horizontal stroke
		'isinsv' => 8947, //  element of with vertical bar at end of horizontal stroke
		'isins' => 8948, //  small element of with vertical bar at end of horizontal stroke
		'isindot' => 8949, //  element of with dot above
		'notinvc' => 8950, //  element of with overbar
		'notinvb' => 8951, //  small element of with overbar
		'isinE' => 8953, //  element of with two horizontal strokes
		'nisd' => 8954, //  contains with long horizontal stroke
		'xnis' => 8955, //  contains with vertical bar at end of horizontal stroke
		'nis' => 8956, //  small contains with vertical bar at end of horizontal stroke
		'notnivc' => 8957, //  contains with overbar
		'notnivb' => 8958, //  small contains with overbar
		'barwed' => 8965, //  projective
		'barwedge' => 8965,
		'Barwed' => 8966, //  perspective
		'doublebarwedge' => 8966,
		'lceil' => 8968, //  left ceiling
		'LeftCeiling' => 8968,
		'rceil' => 8969, //  right ceiling
		'RightCeiling' => 8969,
		'lfloor' => 8970, //  left floor
		'LeftFloor' => 8970,
		'rfloor' => 8971, //  right floor
		'RightFloor' => 8971,
		'drcrop' => 8972, //  bottom right crop
		'dlcrop' => 8973, //  bottom left crop
		'urcrop' => 8974, //  top right crop
		'ulcrop' => 8975, //  top left crop
		'bnot' => 8976, //  reversed not sign
		'profline' => 8978, //  arc
		'profsurf' => 8979, //  segment
		'telrec' => 8981, //  telephone recorder
		'target' => 8982, //  position indicator
		'ulcorn' => 8988, //  top left corner
		'ulcorner' => 8988,
		'urcorn' => 8989, //  top right corner
		'urcorner' => 8989,
		'dlcorn' => 8990, //  bottom left corner
		'llcorner' => 8990,
		'drcorn' => 8991, //  bottom right corner
		'lrcorner' => 8991,
		'frown' => 8994, //  frown
		'sfrown' => 8994,
		'smile' => 8995, //  smile
		'ssmile' => 8995,
		'cylcty' => 9005, //  cylindricity
		'profalar' => 9006, //  all around-profile
		'topbot' => 9014, //  apl functional symbol i-beam
		'ovbar' => 9021, //  apl functional symbol circle stile
		'solbar' => 9023, //  apl functional symbol slash bar
		'angzarr' => 9084, //  right angle with downwards zigzag arrow
		'lmoust' => 9136, //  upper left or lower right curly bracket section
		'lmoustache' => 9136,
		'rmoust' => 9137, //  upper right or lower left curly bracket section
		'rmoustache' => 9137,
		'tbrk' => 9140, //  top square bracket
		'OverBracket' => 9140,
		'bbrk' => 9141, //  bottom square bracket
		'UnderBracket' => 9141,
		'bbrktbrk' => 9142, //  bottom square bracket over top square bracket
		'OverParenthesis' => 9180, //  top parenthesis
		'UnderParenthesis' => 9181, //  bottom parenthesis
		'OverBrace' => 9182, //  top curly bracket
		'UnderBrace' => 9183, //  bottom curly bracket
		'trpezium' => 9186, //  white trapezium
		'elinters' => 9191, //  electrical intersection
		'blank' => 9251, //  open box
		'oS' => 9416, //  circled latin capital letter s
		'circledS' => 9416,
		'boxh' => 9472, //  box drawings light horizontal
		'HorizontalLine' => 9472,
		'boxv' => 9474, //  box drawings light vertical
		'boxdr' => 9484, //  box drawings light down and right
		'boxdl' => 9488, //  box drawings light down and left
		'boxur' => 9492, //  box drawings light up and right
		'boxul' => 9496, //  box drawings light up and left
		'boxvr' => 9500, //  box drawings light vertical and right
		'boxvl' => 9508, //  box drawings light vertical and left
		'boxhd' => 9516, //  box drawings light down and horizontal
		'boxhu' => 9524, //  box drawings light up and horizontal
		'boxvh' => 9532, //  box drawings light vertical and horizontal
		'boxH' => 9552, //  box drawings double horizontal
		'boxV' => 9553, //  box drawings double vertical
		'boxdR' => 9554, //  box drawings down single and right double
		'boxDr' => 9555, //  box drawings down double and right single
		'boxDR' => 9556, //  box drawings double down and right
		'boxdL' => 9557, //  box drawings down single and left double
		'boxDl' => 9558, //  box drawings down double and left single
		'boxDL' => 9559, //  box drawings double down and left
		'boxuR' => 9560, //  box drawings up single and right double
		'boxUr' => 9561, //  box drawings up double and right single
		'boxUR' => 9562, //  box drawings double up and right
		'boxuL' => 9563, //  box drawings up single and left double
		'boxUl' => 9564, //  box drawings up double and left single
		'boxUL' => 9565, //  box drawings double up and left
		'boxvR' => 9566, //  box drawings vertical single and right double
		'boxVr' => 9567, //  box drawings vertical double and right single
		'boxVR' => 9568, //  box drawings double vertical and right
		'boxvL' => 9569, //  box drawings vertical single and left double
		'boxVl' => 9570, //  box drawings vertical double and left single
		'boxVL' => 9571, //  box drawings double vertical and left
		'boxHd' => 9572, //  box drawings down single and horizontal double
		'boxhD' => 9573, //  box drawings down double and horizontal single
		'boxHD' => 9574, //  box drawings double down and horizontal
		'boxHu' => 9575, //  box drawings up single and horizontal double
		'boxhU' => 9576, //  box drawings up double and horizontal single
		'boxHU' => 9577, //  box drawings double up and horizontal
		'boxvH' => 9578, //  box drawings vertical single and horizontal double
		'boxVh' => 9579, //  box drawings vertical double and horizontal single
		'boxVH' => 9580, //  box drawings double vertical and horizontal
		'uhblk' => 9600, //  upper half block
		'lhblk' => 9604, //  lower half block
		'block' => 9608, //  full block
		'blk14' => 9617, //  light shade
		'blk12' => 9618, //  medium shade
		'blk34' => 9619, //  dark shade
		'squ' => 9633, //  white square
		'square' => 9633,
		'Square' => 9633,
		'squf' => 9642, //  black small square
		'squarf' => 9642,
		'blacksquare' => 9642,
		'FilledVerySmallSquare' => 9642,
		'EmptyVerySmallSquare' => 9643, //  white small square
		'rect' => 9645, //  white rectangle
		'marker' => 9646, //  black vertical rectangle
		'fltns' => 9649, //  white parallelogram
		'xutri' => 9651, //  white up-pointing triangle
		'bigtriangleup' => 9651,
		'utrif' => 9652, //  black up-pointing small triangle
		'blacktriangle' => 9652,
		'utri' => 9653, //  white up-pointing small triangle
		'triangle' => 9653,
		'rtrif' => 9656, //  black right-pointing small triangle
		'blacktriangleright' => 9656,
		'rtri' => 9657, //  white right-pointing small triangle
		'triangleright' => 9657,
		'xdtri' => 9661, //  white down-pointing triangle
		'bigtriangledown' => 9661,
		'dtrif' => 9662, //  black down-pointing small triangle
		'blacktriangledown' => 9662,
		'dtri' => 9663, //  white down-pointing small triangle
		'triangledown' => 9663,
		'ltrif' => 9666, //  black left-pointing small triangle
		'blacktriangleleft' => 9666,
		'ltri' => 9667, //  white left-pointing small triangle
		'triangleleft' => 9667,
		'loz' => 9674, //  lozenge
		'lozenge' => 9674,
		'cir' => 9675, //  white circle
		'tridot' => 9708, //  white up-pointing triangle with dot
		'xcirc' => 9711, //  large circle
		'bigcirc' => 9711,
		'ultri' => 9720, //  upper left triangle
		'urtri' => 9721, //  upper right triangle
		'lltri' => 9722, //  lower left triangle
		'EmptySmallSquare' => 9723, //  white medium square
		'FilledSmallSquare' => 9724, //  black medium square
		'starf' => 9733, //  black star
		'bigstar' => 9733,
		'star' => 9734, //  white star
		'phone' => 9742, //  black telephone
		'female' => 9792, //  female sign
		'male' => 9794, //  male sign
		'spades' => 9824, //  black spade suit
		'spadesuit' => 9824,
		'clubs' => 9827, //  black club suit
		'clubsuit' => 9827,
		'hearts' => 9829, //  black heart suit
		'heartsuit' => 9829,
		'diams' => 9830, //  black diamond suit
		'diamondsuit' => 9830,
		'sung' => 9834, //  eighth note
		'flat' => 9837, //  music flat sign
		'natur' => 9838, //  music natural sign
		'natural' => 9838,
		'sharp' => 9839, //  music sharp sign
		'check' => 10003, //  check mark
		'checkmark' => 10003,
		'cross' => 10007, //  ballot x
		'malt' => 10016, //  maltese cross
		'maltese' => 10016,
		'sext' => 10038, //  six pointed black star
		'VerticalSeparator' => 10072, //  light vertical bar
		'lbbrk' => 10098, //  light left tortoise shell bracket ornament
		'rbbrk' => 10099, //  light right tortoise shell bracket ornament
		'lobrk' => 10214, //  mathematical left white square bracket
		'LeftDoubleBracket' => 10214,
		'robrk' => 10215, //  mathematical right white square bracket
		'RightDoubleBracket' => 10215,
		'lang' => 10216, //  mathematical left angle bracket
		'LeftAngleBracket' => 10216,
		'langle' => 10216,
		'rang' => 10217, //  mathematical right angle bracket
		'RightAngleBracket' => 10217,
		'rangle' => 10217,
		'Lang' => 10218, //  mathematical left double angle bracket
		'Rang' => 10219, //  mathematical right double angle bracket
		'loang' => 10220, //  mathematical left white tortoise shell bracket
		'roang' => 10221, //  mathematical right white tortoise shell bracket
		'xlarr' => 10229, //  long leftwards arrow
		'longleftarrow' => 10229,
		'LongLeftArrow' => 10229,
		'xrarr' => 10230, //  long rightwards arrow
		'longrightarrow' => 10230,
		'LongRightArrow' => 10230,
		'xharr' => 10231, //  long left right arrow
		'longleftrightarrow' => 10231,
		'LongLeftRightArrow' => 10231,
		'xlArr' => 10232, //  long leftwards double arrow
		'Longleftarrow' => 10232,
		'DoubleLongLeftArrow' => 10232,
		'xrArr' => 10233, //  long rightwards double arrow
		'Longrightarrow' => 10233,
		'DoubleLongRightArrow' => 10233,
		'xhArr' => 10234, //  long left right double arrow
		'Longleftrightarrow' => 10234,
		'DoubleLongLeftRightArrow' => 10234,
		'xmap' => 10236, //  long rightwards arrow from bar
		'longmapsto' => 10236,
		'dzigrarr' => 10239, //  long rightwards squiggle arrow
		'nvlArr' => 10498, //  leftwards double arrow with vertical stroke
		'nvrArr' => 10499, //  rightwards double arrow with vertical stroke
		'nvHarr' => 10500, //  left right double arrow with vertical stroke
		'Map' => 10501, //  rightwards two-headed arrow from bar
		'lbarr' => 10508, //  leftwards double dash arrow
		'rbarr' => 10509, //  rightwards double dash arrow
		'bkarow' => 10509,
		'lBarr' => 10510, //  leftwards triple dash arrow
		'rBarr' => 10511, //  rightwards triple dash arrow
		'dbkarow' => 10511,
		'RBarr' => 10512, //  rightwards two-headed triple dash arrow
		'drbkarow' => 10512,
		'DDotrahd' => 10513, //  rightwards arrow with dotted stem
		'UpArrowBar' => 10514, //  upwards arrow to bar
		'DownArrowBar' => 10515, //  downwards arrow to bar
		'Rarrtl' => 10518, //  rightwards two-headed arrow with tail
		'latail' => 10521, //  leftwards arrow-tail
		'ratail' => 10522, //  rightwards arrow-tail
		'lAtail' => 10523, //  leftwards double arrow-tail
		'rAtail' => 10524, //  rightwards double arrow-tail
		'larrfs' => 10525, //  leftwards arrow to black diamond
		'rarrfs' => 10526, //  rightwards arrow to black diamond
		'larrbfs' => 10527, //  leftwards arrow from bar to black diamond
		'rarrbfs' => 10528, //  rightwards arrow from bar to black diamond
		'nwarhk' => 10531, //  north west arrow with hook
		'nearhk' => 10532, //  north east arrow with hook
		'searhk' => 10533, //  south east arrow with hook
		'hksearow' => 10533,
		'swarhk' => 10534, //  south west arrow with hook
		'hkswarow' => 10534,
		'nwnear' => 10535, //  north west arrow and north east arrow
		'nesear' => 10536, //  north east arrow and south east arrow
		'toea' => 10536,
		'seswar' => 10537, //  south east arrow and south west arrow
		'tosa' => 10537,
		'swnwar' => 10538, //  south west arrow and north west arrow
		'rarrc' => 10547, //  wave arrow pointing directly right
		'cudarrr' => 10549, //  arrow pointing rightwards then curving downwards
		'ldca' => 10550, //  arrow pointing downwards then curving leftwards
		'rdca' => 10551, //  arrow pointing downwards then curving rightwards
		'cudarrl' => 10552, //  right-side arc clockwise arrow
		'larrpl' => 10553, //  left-side arc anticlockwise arrow
		'curarrm' => 10556, //  top arc clockwise arrow with minus
		'cularrp' => 10557, //  top arc anticlockwise arrow with plus
		'rarrpl' => 10565, //  rightwards arrow with plus below
		'harrcir' => 10568, //  left right arrow through small circle
		'Uarrocir' => 10569, //  upwards two-headed arrow from small circle
		'lurdshar' => 10570, //  left barb up right barb down harpoon
		'ldrushar' => 10571, //  left barb down right barb up harpoon
		'LeftRightVector' => 10574, //  left barb up right barb up harpoon
		'RightUpDownVector' => 10575, //  up barb right down barb right harpoon
		'DownLeftRightVector' => 10576, //  left barb down right barb down harpoon
		'LeftUpDownVector' => 10577, //  up barb left down barb left harpoon
		'LeftVectorBar' => 10578, //  leftwards harpoon with barb up to bar
		'RightVectorBar' => 10579, //  rightwards harpoon with barb up to bar
		'RightUpVectorBar' => 10580, //  upwards harpoon with barb right to bar
		'RightDownVectorBar' => 10581, //  downwards harpoon with barb right to bar
		'DownLeftVectorBar' => 10582, //  leftwards harpoon with barb down to bar
		'DownRightVectorBar' => 10583, //  rightwards harpoon with barb down to bar
		'LeftUpVectorBar' => 10584, //  upwards harpoon with barb left to bar
		'LeftDownVectorBar' => 10585, //  downwards harpoon with barb left to bar
		'LeftTeeVector' => 10586, //  leftwards harpoon with barb up from bar
		'RightTeeVector' => 10587, //  rightwards harpoon with barb up from bar
		'RightUpTeeVector' => 10588, //  upwards harpoon with barb right from bar
		'RightDownTeeVector' => 10589, //  downwards harpoon with barb right from bar
		'DownLeftTeeVector' => 10590, //  leftwards harpoon with barb down from bar
		'DownRightTeeVector' => 10591, //  rightwards harpoon with barb down from bar
		'LeftUpTeeVector' => 10592, //  upwards harpoon with barb left from bar
		'LeftDownTeeVector' => 10593, //  downwards harpoon with barb left from bar
		'lHar' => 10594, //  leftwards harpoon with barb up above leftwards harpoon with barb down
		'uHar' => 10595, //  upwards harpoon with barb left beside upwards harpoon with barb right
		'rHar' => 10596, //  rightwards harpoon with barb up above rightwards harpoon with barb down
		'dHar' => 10597, //  downwards harpoon with barb left beside downwards harpoon with barb right
		'luruhar' => 10598, //  leftwards harpoon with barb up above rightwards harpoon with barb up
		'ldrdhar' => 10599, //  leftwards harpoon with barb down above rightwards harpoon with barb down
		'ruluhar' => 10600, //  rightwards harpoon with barb up above leftwards harpoon with barb up
		'rdldhar' => 10601, //  rightwards harpoon with barb down above leftwards harpoon with barb down
		'lharul' => 10602, //  leftwards harpoon with barb up above long dash
		'llhard' => 10603, //  leftwards harpoon with barb down below long dash
		'rharul' => 10604, //  rightwards harpoon with barb up above long dash
		'lrhard' => 10605, //  rightwards harpoon with barb down below long dash
		'udhar' => 10606, //  upwards harpoon with barb left beside downwards harpoon with barb right
		'UpEquilibrium' => 10606,
		'duhar' => 10607, //  downwards harpoon with barb left beside upwards harpoon with barb right
		'ReverseUpEquilibrium' => 10607,
		'RoundImplies' => 10608, //  right double arrow with rounded head
		'erarr' => 10609, //  equals sign above rightwards arrow
		'simrarr' => 10610, //  tilde operator above rightwards arrow
		'larrsim' => 10611, //  leftwards arrow above tilde operator
		'rarrsim' => 10612, //  rightwards arrow above tilde operator
		'rarrap' => 10613, //  rightwards arrow above almost equal to
		'ltlarr' => 10614, //  less-than above leftwards arrow
		'gtrarr' => 10616, //  greater-than above rightwards arrow
		'subrarr' => 10617, //  subset above rightwards arrow
		'suplarr' => 10619, //  superset above leftwards arrow
		'lfisht' => 10620, //  left fish tail
		'rfisht' => 10621, //  right fish tail
		'ufisht' => 10622, //  up fish tail
		'dfisht' => 10623, //  down fish tail
		'lopar' => 10629, //  left white parenthesis
		'ropar' => 10630, //  right white parenthesis
		'lbrke' => 10635, //  left square bracket with underbar
		'rbrke' => 10636, //  right square bracket with underbar
		'lbrkslu' => 10637, //  left square bracket with tick in top corner
		'rbrksld' => 10638, //  right square bracket with tick in bottom corner
		'lbrksld' => 10639, //  left square bracket with tick in bottom corner
		'rbrkslu' => 10640, //  right square bracket with tick in top corner
		'langd' => 10641, //  left angle bracket with dot
		'rangd' => 10642, //  right angle bracket with dot
		'lparlt' => 10643, //  left arc less-than bracket
		'rpargt' => 10644, //  right arc greater-than bracket
		'gtlPar' => 10645, //  double left arc greater-than bracket
		'ltrPar' => 10646, //  double right arc less-than bracket
		'vzigzag' => 10650, //  vertical zigzag line
		'vangrt' => 10652, //  right angle variant with square
		'angrtvbd' => 10653, //  measured right angle with dot
		'ange' => 10660, //  angle with underbar
		'range' => 10661, //  reversed angle with underbar
		'dwangle' => 10662, //  oblique angle opening up
		'uwangle' => 10663, //  oblique angle opening down
		'angmsdaa' => 10664, //  measured angle with open arm ending in arrow pointing up and right
		'angmsdab' => 10665, //  measured angle with open arm ending in arrow pointing up and left
		'angmsdac' => 10666, //  measured angle with open arm ending in arrow pointing down and right
		'angmsdad' => 10667, //  measured angle with open arm ending in arrow pointing down and left
		'angmsdae' => 10668, //  measured angle with open arm ending in arrow pointing right and up
		'angmsdaf' => 10669, //  measured angle with open arm ending in arrow pointing left and up
		'angmsdag' => 10670, //  measured angle with open arm ending in arrow pointing right and down
		'angmsdah' => 10671, //  measured angle with open arm ending in arrow pointing left and down
		'bemptyv' => 10672, //  reversed empty set
		'demptyv' => 10673, //  empty set with overbar
		'cemptyv' => 10674, //  empty set with small circle above
		'raemptyv' => 10675, //  empty set with right arrow above
		'laemptyv' => 10676, //  empty set with left arrow above
		'ohbar' => 10677, //  circle with horizontal bar
		'omid' => 10678, //  circled vertical bar
		'opar' => 10679, //  circled parallel
		'operp' => 10681, //  circled perpendicular
		'olcross' => 10683, //  circle with superimposed x
		'odsold' => 10684, //  circled anticlockwise-rotated division sign
		'olcir' => 10686, //  circled white bullet
		'ofcir' => 10687, //  circled bullet
		'olt' => 10688, //  circled less-than
		'ogt' => 10689, //  circled greater-than
		'cirscir' => 10690, //  circle with small circle to the right
		'cirE' => 10691, //  circle with two horizontal strokes to the right
		'solb' => 10692, //  squared rising diagonal slash
		'bsolb' => 10693, //  squared falling diagonal slash
		'boxbox' => 10697, //  two joined squares
		'trisb' => 10701, //  triangle with serifs at bottom
		'rtriltri' => 10702, //  right triangle above left triangle
		'LeftTriangleBar' => 10703, //  left triangle beside vertical bar
		'RightTriangleBar' => 10704, //  vertical bar beside right triangle
		'race' => 10714, //  left double wiggly fence
		'iinfin' => 10716, //  incomplete infinity
		'infintie' => 10717, //  tie over infinity
		'nvinfin' => 10718, //  infinity negated with vertical bar
		'eparsl' => 10723, //  equals sign and slanted parallel
		'smeparsl' => 10724, //  equals sign and slanted parallel with tilde above
		'eqvparsl' => 10725, //  identical to and slanted parallel
		'lozf' => 10731, //  black lozenge
		'blacklozenge' => 10731,
		'RuleDelayed' => 10740, //  rule-delayed
		'dsol' => 10742, //  solidus with overbar
		'xodot' => 10752, //  n-ary circled dot operator
		'bigodot' => 10752,
		'xoplus' => 10753, //  n-ary circled plus operator
		'bigoplus' => 10753,
		'xotime' => 10754, //  n-ary circled times operator
		'bigotimes' => 10754,
		'xuplus' => 10756, //  n-ary union operator with plus
		'biguplus' => 10756,
		'xsqcup' => 10758, //  n-ary square union operator
		'bigsqcup' => 10758,
		'qint' => 10764, //  quadruple integral operator
		'iiiint' => 10764,
		'fpartint' => 10765, //  finite part integral
		'cirfnint' => 10768, //  circulation function
		'awint' => 10769, //  anticlockwise integration
		'rppolint' => 10770, //  line integration with rectangular path around pole
		'scpolint' => 10771, //  line integration with semicircular path around pole
		'npolint' => 10772, //  line integration not including the pole
		'pointint' => 10773, //  integral around a point operator
		'quatint' => 10774, //  quaternion integral operator
		'intlarhk' => 10775, //  integral with leftwards arrow with hook
		'pluscir' => 10786, //  plus sign with small circle above
		'plusacir' => 10787, //  plus sign with circumflex accent above
		'simplus' => 10788, //  plus sign with tilde above
		'plusdu' => 10789, //  plus sign with dot below
		'plussim' => 10790, //  plus sign with tilde below
		'plustwo' => 10791, //  plus sign with subscript two
		'mcomma' => 10793, //  minus sign with comma above
		'minusdu' => 10794, //  minus sign with dot below
		'loplus' => 10797, //  plus sign in left half circle
		'roplus' => 10798, //  plus sign in right half circle
		'Cross' => 10799, //  vector or cross product
		'timesd' => 10800, //  multiplication sign with dot above
		'timesbar' => 10801, //  multiplication sign with underbar
		'smashp' => 10803, //  smash product
		'lotimes' => 10804, //  multiplication sign in left half circle
		'rotimes' => 10805, //  multiplication sign in right half circle
		'otimesas' => 10806, //  circled multiplication sign with circumflex accent
		'Otimes' => 10807, //  multiplication sign in double circle
		'odiv' => 10808, //  circled division sign
		'triplus' => 10809, //  plus sign in triangle
		'triminus' => 10810, //  minus sign in triangle
		'tritime' => 10811, //  multiplication sign in triangle
		'iprod' => 10812, //  interior product
		'intprod' => 10812,
		'amalg' => 10815, //  amalgamation or coproduct
		'capdot' => 10816, //  intersection with dot
		'ncup' => 10818, //  union with overbar
		'ncap' => 10819, //  intersection with overbar
		'capand' => 10820, //  intersection with logical and
		'cupor' => 10821, //  union with logical or
		'cupcap' => 10822, //  union above intersection
		'capcup' => 10823, //  intersection above union
		'cupbrcap' => 10824, //  union above bar above intersection
		'capbrcup' => 10825, //  intersection above bar above union
		'cupcup' => 10826, //  union beside and joined with union
		'capcap' => 10827, //  intersection beside and joined with intersection
		'ccups' => 10828, //  closed union with serifs
		'ccaps' => 10829, //  closed intersection with serifs
		'ccupssm' => 10832, //  closed union with serifs and smash product
		'And' => 10835, //  double logical and
		'Or' => 10836, //  double logical or
		'andand' => 10837, //  two intersecting logical and
		'oror' => 10838, //  two intersecting logical or
		'orslope' => 10839, //  sloping large or
		'andslope' => 10840, //  sloping large and
		'andv' => 10842, //  logical and with middle stem
		'orv' => 10843, //  logical or with middle stem
		'andd' => 10844, //  logical and with horizontal dash
		'ord' => 10845, //  logical or with horizontal dash
		'wedbar' => 10847, //  logical and with underbar
		'sdote' => 10854, //  equals sign with dot below
		'simdot' => 10858, //  tilde operator with dot above
		'congdot' => 10861, //  congruent with dot above
		'easter' => 10862, //  equals with asterisk
		'apacir' => 10863, //  almost equal to with circumflex accent
		'apE' => 10864, //  approximately equal or equal to
		'eplus' => 10865, //  equals sign above plus sign
		'pluse' => 10866, //  plus sign above equals sign
		'Esim' => 10867, //  equals sign above tilde operator
		'Colone' => 10868, //  double colon equal
		'Equal' => 10869, //  two consecutive equals signs
		'eDDot' => 10871, //  equals sign with two dots above and two dots below
		'ddotseq' => 10871,
		'equivDD' => 10872, //  equivalent with four dots above
		'ltcir' => 10873, //  less-than with circle inside
		'gtcir' => 10874, //  greater-than with circle inside
		'ltquest' => 10875, //  less-than with question mark above
		'gtquest' => 10876, //  greater-than with question mark above
		'les' => 10877, //  less-than or slanted equal to
		'LessSlantEqual' => 10877,
		'leqslant' => 10877,
		'ges' => 10878, //  greater-than or slanted equal to
		'GreaterSlantEqual' => 10878,
		'geqslant' => 10878,
		'lesdot' => 10879, //  less-than or slanted equal to with dot inside
		'gesdot' => 10880, //  greater-than or slanted equal to with dot inside
		'lesdoto' => 10881, //  less-than or slanted equal to with dot above
		'gesdoto' => 10882, //  greater-than or slanted equal to with dot above
		'lesdotor' => 10883, //  less-than or slanted equal to with dot above right
		'gesdotol' => 10884, //  greater-than or slanted equal to with dot above left
		'lap' => 10885, //  less-than or approximate
		'lessapprox' => 10885,
		'gap' => 10886, //  greater-than or approximate
		'gtrapprox' => 10886,
		'lne' => 10887, //  less-than and single-line not equal to
		'lneq' => 10887,
		'gne' => 10888, //  greater-than and single-line not equal to
		'gneq' => 10888,
		'lnap' => 10889, //  less-than and not approximate
		'lnapprox' => 10889,
		'gnap' => 10890, //  greater-than and not approximate
		'gnapprox' => 10890,
		'lEg' => 10891, //  less-than above double-line equal above greater-than
		'lesseqqgtr' => 10891,
		'gEl' => 10892, //  greater-than above double-line equal above less-than
		'gtreqqless' => 10892,
		'lsime' => 10893, //  less-than above similar or equal
		'gsime' => 10894, //  greater-than above similar or equal
		'lsimg' => 10895, //  less-than above similar above greater-than
		'gsiml' => 10896, //  greater-than above similar above less-than
		'lgE' => 10897, //  less-than above greater-than above double-line equal
		'glE' => 10898, //  greater-than above less-than above double-line equal
		'lesges' => 10899, //  less-than above slanted equal above greater-than above slanted equal
		'gesles' => 10900, //  greater-than above slanted equal above less-than above slanted equal
		'els' => 10901, //  slanted equal to or less-than
		'eqslantless' => 10901,
		'egs' => 10902, //  slanted equal to or greater-than
		'eqslantgtr' => 10902,
		'elsdot' => 10903, //  slanted equal to or less-than with dot inside
		'egsdot' => 10904, //  slanted equal to or greater-than with dot inside
		'el' => 10905, //  double-line equal to or less-than
		'eg' => 10906, //  double-line equal to or greater-than
		'siml' => 10909, //  similar or less-than
		'simg' => 10910, //  similar or greater-than
		'simlE' => 10911, //  similar above less-than above equals sign
		'simgE' => 10912, //  similar above greater-than above equals sign
		'LessLess' => 10913, //  double nested less-than
		'GreaterGreater' => 10914, //  double nested greater-than
		'glj' => 10916, //  greater-than overlapping less-than
		'gla' => 10917, //  greater-than beside less-than
		'ltcc' => 10918, //  less-than closed by curve
		'gtcc' => 10919, //  greater-than closed by curve
		'lescc' => 10920, //  less-than closed by curve above slanted equal
		'gescc' => 10921, //  greater-than closed by curve above slanted equal
		'smt' => 10922, //  smaller than
		'lat' => 10923, //  larger than
		'smte' => 10924, //  smaller than or equal to
		'late' => 10925, //  larger than or equal to
		'bumpE' => 10926, //  equals sign with bumpy above
		'pre' => 10927, //  precedes above single-line equals sign
		'preceq' => 10927,
		'PrecedesEqual' => 10927,
		'sce' => 10928, //  succeeds above single-line equals sign
		'succeq' => 10928,
		'SucceedsEqual' => 10928,
		'prE' => 10931, //  precedes above equals sign
		'scE' => 10932, //  succeeds above equals sign
		'prnE' => 10933, //  precedes above not equal to
		'precneqq' => 10933,
		'scnE' => 10934, //  succeeds above not equal to
		'succneqq' => 10934,
		'prap' => 10935, //  precedes above almost equal to
		'precapprox' => 10935,
		'scap' => 10936, //  succeeds above almost equal to
		'succapprox' => 10936,
		'prnap' => 10937, //  precedes above not almost equal to
		'precnapprox' => 10937,
		'scnap' => 10938, //  succeeds above not almost equal to
		'succnapprox' => 10938,
		'Pr' => 10939, //  double precedes
		'Sc' => 10940, //  double succeeds
		'subdot' => 10941, //  subset with dot
		'supdot' => 10942, //  superset with dot
		'subplus' => 10943, //  subset with plus sign below
		'supplus' => 10944, //  superset with plus sign below
		'submult' => 10945, //  subset with multiplication sign below
		'supmult' => 10946, //  superset with multiplication sign below
		'subedot' => 10947, //  subset of or equal to with dot above
		'supedot' => 10948, //  superset of or equal to with dot above
		'subE' => 10949, //  subset of above equals sign
		'subseteqq' => 10949,
		'supE' => 10950, //  superset of above equals sign
		'supseteqq' => 10950,
		'subsim' => 10951, //  subset of above tilde operator
		'supsim' => 10952, //  superset of above tilde operator
		'subnE' => 10955, //  subset of above not equal to
		'subsetneqq' => 10955,
		'supnE' => 10956, //  superset of above not equal to
		'supsetneqq' => 10956,
		'csub' => 10959, //  closed subset
		'csup' => 10960, //  closed superset
		'csube' => 10961, //  closed subset or equal to
		'csupe' => 10962, //  closed superset or equal to
		'subsup' => 10963, //  subset above superset
		'supsub' => 10964, //  superset above subset
		'subsub' => 10965, //  subset above subset
		'supsup' => 10966, //  superset above superset
		'suphsub' => 10967, //  superset beside subset
		'supdsub' => 10968, //  superset beside and joined by dash with subset
		'forkv' => 10969, //  element of opening downwards
		'topfork' => 10970, //  pitchfork with tee top
		'mlcp' => 10971, //  transversal intersection
		'Dashv' => 10980, //  vertical bar double left turnstile
		'DoubleLeftTee' => 10980,
		'Vdashl' => 10982, //  long dash from left member of double vertical
		'Barv' => 10983, //  short down tack with overbar
		'vBar' => 10984, //  short up tack with underbar
		'vBarv' => 10985, //  short up tack above short down tack
		'Vbar' => 10987, //  double up tack
		'Not' => 10988, //  double stroke not sign
		'bNot' => 10989, //  reversed double stroke not sign
		'rnmid' => 10990, //  does not divide with reversed negation slash
		'cirmid' => 10991, //  vertical line with circle above
		'midcir' => 10992, //  vertical line with circle below
		'topcir' => 10993, //  down tack with circle below
		'nhpar' => 10994, //  parallel with horizontal stroke
		'parsim' => 10995, //  parallel with tilde operator
		'parsl' => 11005, //  double solidus operator
		'fflig' => 64256, //  latin small ligature ff
		'filig' => 64257, //  latin small ligature fi
		'fllig' => 64258, //  latin small ligature fl
		'ffilig' => 64259, //  latin small ligature ffi
		'ffllig' => 64260, //  latin small ligature ffl
		'Ascr' => 119964, //  mathematical script capital a
		'Cscr' => 119966, //  mathematical script capital c
		'Dscr' => 119967, //  mathematical script capital d
		'Gscr' => 119970, //  mathematical script capital g
		'Jscr' => 119973, //  mathematical script capital j
		'Kscr' => 119974, //  mathematical script capital k
		'Nscr' => 119977, //  mathematical script capital n
		'Oscr' => 119978, //  mathematical script capital o
		'Pscr' => 119979, //  mathematical script capital p
		'Qscr' => 119980, //  mathematical script capital q
		'Sscr' => 119982, //  mathematical script capital s
		'Tscr' => 119983, //  mathematical script capital t
		'Uscr' => 119984, //  mathematical script capital u
		'Vscr' => 119985, //  mathematical script capital v
		'Wscr' => 119986, //  mathematical script capital w
		'Xscr' => 119987, //  mathematical script capital x
		'Yscr' => 119988, //  mathematical script capital y
		'Zscr' => 119989, //  mathematical script capital z
		'ascr' => 119990, //  mathematical script small a
		'bscr' => 119991, //  mathematical script small b
		'cscr' => 119992, //  mathematical script small c
		'dscr' => 119993, //  mathematical script small d
		'fscr' => 119995, //  mathematical script small f
		'hscr' => 119997, //  mathematical script small h
		'iscr' => 119998, //  mathematical script small i
		'jscr' => 119999, //  mathematical script small j
		'kscr' => 120000, //  mathematical script small k
		'lscr' => 120001, //  mathematical script small l
		'mscr' => 120002, //  mathematical script small m
		'nscr' => 120003, //  mathematical script small n
		'pscr' => 120005, //  mathematical script small p
		'qscr' => 120006, //  mathematical script small q
		'rscr' => 120007, //  mathematical script small r
		'sscr' => 120008, //  mathematical script small s
		'tscr' => 120009, //  mathematical script small t
		'uscr' => 120010, //  mathematical script small u
		'vscr' => 120011, //  mathematical script small v
		'wscr' => 120012, //  mathematical script small w
		'xscr' => 120013, //  mathematical script small x
		'yscr' => 120014, //  mathematical script small y
		'zscr' => 120015, //  mathematical script small z
		'Afr' => 120068, //  mathematical fraktur capital a
		'Bfr' => 120069, //  mathematical fraktur capital b
		'Dfr' => 120071, //  mathematical fraktur capital d
		'Efr' => 120072, //  mathematical fraktur capital e
		'Ffr' => 120073, //  mathematical fraktur capital f
		'Gfr' => 120074, //  mathematical fraktur capital g
		'Jfr' => 120077, //  mathematical fraktur capital j
		'Kfr' => 120078, //  mathematical fraktur capital k
		'Lfr' => 120079, //  mathematical fraktur capital l
		'Mfr' => 120080, //  mathematical fraktur capital m
		'Nfr' => 120081, //  mathematical fraktur capital n
		'Ofr' => 120082, //  mathematical fraktur capital o
		'Pfr' => 120083, //  mathematical fraktur capital p
		'Qfr' => 120084, //  mathematical fraktur capital q
		'Sfr' => 120086, //  mathematical fraktur capital s
		'Tfr' => 120087, //  mathematical fraktur capital t
		'Ufr' => 120088, //  mathematical fraktur capital u
		'Vfr' => 120089, //  mathematical fraktur capital v
		'Wfr' => 120090, //  mathematical fraktur capital w
		'Xfr' => 120091, //  mathematical fraktur capital x
		'Yfr' => 120092, //  mathematical fraktur capital y
		'afr' => 120094, //  mathematical fraktur small a
		'bfr' => 120095, //  mathematical fraktur small b
		'cfr' => 120096, //  mathematical fraktur small c
		'dfr' => 120097, //  mathematical fraktur small d
		'efr' => 120098, //  mathematical fraktur small e
		'ffr' => 120099, //  mathematical fraktur small f
		'gfr' => 120100, //  mathematical fraktur small g
		'hfr' => 120101, //  mathematical fraktur small h
		'ifr' => 120102, //  mathematical fraktur small i
		'jfr' => 120103, //  mathematical fraktur small j
		'kfr' => 120104, //  mathematical fraktur small k
		'lfr' => 120105, //  mathematical fraktur small l
		'mfr' => 120106, //  mathematical fraktur small m
		'nfr' => 120107, //  mathematical fraktur small n
		'ofr' => 120108, //  mathematical fraktur small o
		'pfr' => 120109, //  mathematical fraktur small p
		'qfr' => 120110, //  mathematical fraktur small q
		'rfr' => 120111, //  mathematical fraktur small r
		'sfr' => 120112, //  mathematical fraktur small s
		'tfr' => 120113, //  mathematical fraktur small t
		'ufr' => 120114, //  mathematical fraktur small u
		'vfr' => 120115, //  mathematical fraktur small v
		'wfr' => 120116, //  mathematical fraktur small w
		'xfr' => 120117, //  mathematical fraktur small x
		'yfr' => 120118, //  mathematical fraktur small y
		'zfr' => 120119, //  mathematical fraktur small z
		'Aopf' => 120120, //  mathematical double-struck capital a
		'Bopf' => 120121, //  mathematical double-struck capital b
		'Dopf' => 120123, //  mathematical double-struck capital d
		'Eopf' => 120124, //  mathematical double-struck capital e
		'Fopf' => 120125, //  mathematical double-struck capital f
		'Gopf' => 120126, //  mathematical double-struck capital g
		'Iopf' => 120128, //  mathematical double-struck capital i
		'Jopf' => 120129, //  mathematical double-struck capital j
		'Kopf' => 120130, //  mathematical double-struck capital k
		'Lopf' => 120131, //  mathematical double-struck capital l
		'Mopf' => 120132, //  mathematical double-struck capital m
		'Oopf' => 120134, //  mathematical double-struck capital o
		'Sopf' => 120138, //  mathematical double-struck capital s
		'Topf' => 120139, //  mathematical double-struck capital t
		'Uopf' => 120140, //  mathematical double-struck capital u
		'Vopf' => 120141, //  mathematical double-struck capital v
		'Wopf' => 120142, //  mathematical double-struck capital w
		'Xopf' => 120143, //  mathematical double-struck capital x
		'Yopf' => 120144, //  mathematical double-struck capital y
		'aopf' => 120146, //  mathematical double-struck small a
		'bopf' => 120147, //  mathematical double-struck small b
		'copf' => 120148, //  mathematical double-struck small c
		'dopf' => 120149, //  mathematical double-struck small d
		'eopf' => 120150, //  mathematical double-struck small e
		'fopf' => 120151, //  mathematical double-struck small f
		'gopf' => 120152, //  mathematical double-struck small g
		'hopf' => 120153, //  mathematical double-struck small h
		'iopf' => 120154, //  mathematical double-struck small i
		'jopf' => 120155, //  mathematical double-struck small j
		'kopf' => 120156, //  mathematical double-struck small k
		'lopf' => 120157, //  mathematical double-struck small l
		'mopf' => 120158, //  mathematical double-struck small m
		'nopf' => 120159, //  mathematical double-struck small n
		'oopf' => 120160, //  mathematical double-struck small o
		'popf' => 120161, //  mathematical double-struck small p
		'qopf' => 120162, //  mathematical double-struck small q
		'ropf' => 120163, //  mathematical double-struck small r
		'sopf' => 120164, //  mathematical double-struck small s
		'topf' => 120165, //  mathematical double-struck small t
		'uopf' => 120166, //  mathematical double-struck small u
		'vopf' => 120167, //  mathematical double-struck small v
		'wopf' => 120168, //  mathematical double-struck small w
		'xopf' => 120169, //  mathematical double-struck small x
		'yopf' => 120170, //  mathematical double-struck small y
		'zopf' => 120171, //  mathematical double-struck small z
	);

	/**
	 *  Get the value of the entity, or fall down to custom property
	 *  @name   get
	 *  @type   method
	 *  @access public
	 *  @param  string entity
	 *  @return string value
	 */
	public function get($property, $default=null)
	{
		if (isset(self::$resolve[$property]))
			return self::$resolve[$property];
		return parent::get($property, $default);
	}
}